
name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Dart SDK
      uses: dart-lang/setup-dart@v1.7.1

    - name: Install dependencies
      run: dart pub get

    - name: Analyze project
      run: dart analyze --fatal-infos

    - name: Run tests with coverage
      run: dart test --coverage=coverage --exclude-tags integration

    - name: Generate LCOV report
      run: dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage/lcov.info
        fail_ci_if_error: true